import '@/app/reset.css';
import type { Metadata } from 'next';
import Providers from '@/app/Providers';
import MainContents from '@/app/_layout/MainContents';

export const metadata: Metadata = {
  title: 'moneyger',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <MainContents>{children}</MainContents>
        </Providers>
      </body>
    </html>
  );
}
