import type { Metadata } from 'next';
import Providers from '@/app/Providers';
import MoneygerAppBar from '@/components/common/MoneygerAppBar';
import PageContentsTemplate from '@/components/common/PageContentsTemplate';

export const metadata: Metadata = {
  title: 'moneyger',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <MoneygerAppBar />
          <PageContentsTemplate>{children}</PageContentsTemplate>
        </Providers>
      </body>
    </html>
  );
}
